# Chorus built-in SMTC bridge - Windows sign-in registration.
#
# Registers the hidden launcher under the current user's Run key:
#
#   HKCU\Software\Microsoft\Windows\CurrentVersion\Run  ->  Chorus SMTC Bridge
#
# HKCU rather than HKLM on purpose: no administrator rights, and per-user is what a
# streaming overlay wants. Chorus itself registers as "Chorus", so the two entries
# are independent and either can be removed without disturbing the other.
#
# A Startup-folder `.cmd` is written instead when the registry is not writable
# (locked-down or policy-managed machines), mirroring what Chorus does.
#
# Written for Windows PowerShell 5.1 - no ternary operators, no `??`.

[CmdletBinding()]
param(
  [ValidateSet('Enable', 'Disable', 'Status')]
  [string] $Action = 'Status',

  [int] $Port = 5010,

  # Test seam: point the registry operations somewhere harmless.
  [string] $RegistryRoot = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run',

  [switch] $Quiet
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$ValueName = 'Chorus SMTC Bridge'
$BridgeDir = $PSScriptRoot
$HiddenLauncher = Join-Path $BridgeDir 'bridge-hidden.vbs'
$ServerScript = Join-Path $BridgeDir 'server.ps1'

function Write-Line {
  param([string] $Message, [string] $Colour = '')
  if ($Quiet) { return }
  if ($Colour) { Write-Host $Message -ForegroundColor $Colour } else { Write-Host $Message }
}

function Get-WscriptPath {
  $candidate = Join-Path $env:SystemRoot 'System32\wscript.exe'
  if (Test-Path $candidate) { return $candidate }
  return 'wscript.exe'
}

function Get-StartupFolderEntry {
  if (-not $env:APPDATA) { return $null }
  return Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup\Chorus SMTC Bridge.cmd'
}

function Get-ExpectedCommand {
  # The port travels as an argument to the hidden launcher, so the registration can
  # be changed without editing any file.
  return '"{0}" "{1}" {2}' -f (Get-WscriptPath), $HiddenLauncher, $Port
}

<#
  .SYNOPSIS
    Read the currently registered value, or $null.
#>
function Get-RegisteredCommand {
  try {
    $item = Get-ItemProperty -Path $RegistryRoot -Name $ValueName -ErrorAction Stop
    return [string]$item.$ValueName
  } catch {
    return $null
  }
}

<#
  .SYNOPSIS
    The Startup-folder launcher contents, pointing at this installation.
#>
function Get-StartupLauncherContents {
  return @(
    '@echo off'
    'REM Generated by the Chorus SMTC bridge. Starts it hidden at sign-in.'
    ('start "" "{0}" "{1}" {2}' -f (Get-WscriptPath), $HiddenLauncher, $Port)
    ''
  ) -join "`r`n"
}

function Enable-StartupFolder {
  $target = Get-StartupFolderEntry
  if (-not $target) { return @{ ok = $false; error = 'APPDATA is not set, so the Startup folder cannot be located' } }
  if (-not (Test-Path $HiddenLauncher)) { return @{ ok = $false; error = "the hidden launcher is missing at $HiddenLauncher" } }
  try {
    $dir = Split-Path -Parent $target
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Set-Content -Path $target -Value (Get-StartupLauncherContents) -Encoding ASCII
    return @{ ok = $true; path = $target }
  } catch {
    return @{ ok = $false; error = $_.Exception.Message }
  }
}

function Disable-StartupFolder {
  $target = Get-StartupFolderEntry
  if (-not $target) { return @{ ok = $false; error = 'APPDATA is not set' } }
  try {
    if (Test-Path $target) { Remove-Item $target -Force }
    return @{ ok = $true }
  } catch {
    return @{ ok = $false; error = $_.Exception.Message }
  }
}

function Test-StartupFolderEntry {
  $target = Get-StartupFolderEntry
  if (-not $target) { return $false }
  return (Test-Path $target)
}

function Invoke-Enable {
  if (-not (Test-Path $ServerScript)) {
    Write-Line "  The bridge server is missing: $ServerScript" 'Red'
    return 1
  }
  if (-not (Test-Path $HiddenLauncher)) {
    Write-Line "  The hidden launcher is missing: $HiddenLauncher" 'Red'
    return 1
  }

  $expected = Get-ExpectedCommand

  # Make sure the registry path exists when a test root is used.
  try {
    if (-not (Test-Path $RegistryRoot)) { New-Item -Path $RegistryRoot -Force | Out-Null }
  } catch {
    # Fall through: the write below will report the real problem.
  }

  try {
    New-ItemProperty -Path $RegistryRoot -Name $ValueName -Value $expected -PropertyType String -Force | Out-Null
  } catch {
    # Not writable: fall back to the Startup folder so the feature still works.
    $fallback = Enable-StartupFolder
    if ($fallback.ok) {
      Write-Line "  Registered via the Startup folder instead (the registry was not writable)." 'Yellow'
      Write-Line "  $($fallback.path)" 'DarkGray'
      return 0
    }
    Write-Line "  Could not register auto-start." 'Red'
    Write-Line "    registry: $($_.Exception.Message)" 'Red'
    Write-Line "    Startup folder: $($fallback.error)" 'Red'
    return 1
  }

  # Keep the two mechanisms from both firing.
  [void](Disable-StartupFolder)

  Write-Line "  Auto-start enabled." 'Green'
  Write-Line "    registry : $RegistryRoot\$ValueName" 'DarkGray'
  Write-Line "    command  : $expected" 'DarkGray'
  Write-Line "    port     : $Port" 'DarkGray'
  Write-Line ""
  Write-Line "  The bridge will start hidden at your next sign-in." 'DarkGray'
  Write-Line "  Start it now without signing out:  start.bat $Port" 'DarkGray'
  return 0
}

function Invoke-Disable {
  $removed = $false
  try {
    if (Get-RegisteredCommand) {
      Remove-ItemProperty -Path $RegistryRoot -Name $ValueName -Force
      $removed = $true
    }
  } catch {
    Write-Line "  Could not remove the registry entry: $($_.Exception.Message)" 'Red'
    return 1
  }
  $folder = Disable-StartupFolder
  if ($folder.ok) { $removed = $true }

  if ($removed) {
    Write-Line "  Auto-start disabled." 'Green'
    Write-Line "  A bridge that is already running keeps running until you close it." 'DarkGray'
  } else {
    Write-Line "  Auto-start was not enabled, so there was nothing to remove." 'Yellow'
  }
  return 0
}

function Invoke-Status {
  $registered = Get-RegisteredCommand
  $viaFolder = Test-StartupFolderEntry
  $expected = Get-ExpectedCommand

  $running = $false
  $runningVersion = $null
  try {
    $health = Invoke-WebRequest "http://127.0.0.1:$Port/health" -UseBasicParsing -TimeoutSec 3
    $parsed = $health.Content | ConvertFrom-Json
    if ($parsed.ok) { $running = $true; $runningVersion = $parsed.app_version }
  } catch {
    $running = $false
  }

  Write-Line ""
  Write-Line "  Chorus SMTC bridge" 'White'
  Write-Line "  ------------------"
  if ($registered) {
    Write-Line "  auto-start  : enabled (registry)" 'Green'
    Write-Line "  command     : $registered" 'DarkGray'
    if ($registered -ne $expected) {
      Write-Line "  note        : this differs from what this copy would register" 'Yellow'
      Write-Line "                expected: $expected" 'Yellow'
    }
  } elseif ($viaFolder) {
    Write-Line "  auto-start  : enabled (Startup folder)" 'Green'
    Write-Line "  entry       : $(Get-StartupFolderEntry)" 'DarkGray'
  } else {
    Write-Line "  auto-start  : disabled" 'Yellow'
  }

  if ($running) {
    Write-Line "  running now : yes (v$runningVersion on port $Port)" 'Green'
  } else {
    Write-Line "  running now : no" 'Yellow'
  }
  Write-Line ""
  return 0
}

switch ($Action) {
  'Enable' { exit (Invoke-Enable) }
  'Disable' { exit (Invoke-Disable) }
  default { exit (Invoke-Status) }
}
