/**
 * Windows auto-start management.
 *
 * Registers Chorus under the current user's Run key:
 *
 *   HKCU\Software\Microsoft\Windows\CurrentVersion\Run  →  Chorus
 *
 * HKCU is used rather than HKLM deliberately: it needs no administrator rights,
 * and it is per-user, which is what a streaming overlay wants.
 *
 * IMPORTANT IMPLEMENTATION NOTE
 * reg.exe is launched with `stdio: 'ignore'` and judged only by its exit code.
 * Capturing its output would require stdio pipes, which confined Windows
 * environments can refuse with EPERM — and because this module runs during
 * startup, that failure would stop the server from starting at all. Exit codes
 * are sufficient: `reg query` returns non-zero when the value is absent, and
 * `reg add` / `reg delete` return zero on success.
 */

import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from '../config.js';

const RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';
const VALUE_NAME = 'Chorus';

/**
 * Startup-folder entry, used only when the registry is not writable.
 *
 * A `.cmd` rather than a `.lnk`: it is generated on the spot, so it always points
 * at wherever Chorus actually lives. A committed shortcut would embed the author's
 * absolute paths (a .lnk stores them in its binary ID list) and break as soon as
 * the folder moved. Running wscript.exe from a .cmd launches the hidden helper
 * without opening a console window, because wscript is a GUI host.
 */
const STARTUP_ENTRY = 'Chorus.cmd';

function startupEntryPath() {
  const appData = process.env.APPDATA;
  if (!appData) return null;
  return path.join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', STARTUP_ENTRY);
}

/** The contents of the Startup-folder launcher, pointing at this installation. */
function startupLauncherScript() {
  return [
    '@echo off',
    'REM Generated by Chorus. Starts it hidden in the background at sign-in.',
    `start "" "${WSCRIPT}" "${HIDDEN_LAUNCHER}"`,
    '',
  ].join('\r\n');
}

/**
 * Register via the Startup folder instead of the registry. The fallback for
 * locked-down or policy-managed machines where the Run key cannot be written.
 */
function enableViaStartupFolder() {
  const target = startupEntryPath();
  if (!target) return { ok: false, error: 'APPDATA is not set, so the Startup folder cannot be located' };
  if (!fs.existsSync(HIDDEN_LAUNCHER)) {
    return { ok: false, error: `the hidden launcher is missing at ${HIDDEN_LAUNCHER}` };
  }
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, startupLauncherScript(), 'utf8');
    return { ok: true, method: 'startup-folder', path: target };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

function disableViaStartupFolder() {
  const target = startupEntryPath();
  if (!target) return { ok: false, error: 'APPDATA is not set' };
  try {
    fs.rmSync(target, { force: true });
    // Clean up an entry written by an earlier version.
    fs.rmSync(target.replace(/Chorus\.cmd$/, 'Chorus.lnk'), { force: true });
    return { ok: true, method: 'startup-folder' };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

function shortcutExists() {
  const target = startupEntryPath();
  return Boolean(target) && fs.existsSync(target);
}

export const WSCRIPT = path.join(process.env.SystemRoot ?? 'C:\\Windows', 'System32', 'wscript.exe');
export const HIDDEN_LAUNCHER = path.join(ROOT, 'launcher', 'chorus-hidden.vbs');

/** The exact command line Windows will run at sign-in. */
export function autostartCommand() {
  return `"${WSCRIPT}" "${HIDDEN_LAUNCHER}"`;
}

/**
 * Run reg.exe and resolve with its exit code. `ok` is true for exit code 0.
 * Never rejects: auto-start problems must not break startup.
 */
function runReg(args, { timeoutMs = 8000 } = {}) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn('reg.exe', args, {
        windowsHide: true,
        // No pipes: output capture can be denied in confined environments.
        stdio: 'ignore',
        detached: false,
      });
    } catch (err) {
      resolve({ ok: false, code: null, error: err.message });
      return;
    }

    let settled = false;
    const finish = (result) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(result);
    };

    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        /* ignore */
      }
      finish({ ok: false, code: null, error: 'reg.exe timed out' });
    }, timeoutMs);
    if (timer.unref) timer.unref();

    child.on('error', (err) => finish({ ok: false, code: null, error: err.message }));
    child.on('close', (code) => finish({ ok: code === 0, code, error: code === 0 ? null : `reg.exe exited with code ${code}` }));
  });
}

/**
 * @returns {Promise<{enabled:boolean, command:string|null, expected:string, supported:boolean, stale?:boolean}>}
 */
export async function getAutostartStatus() {
  const expected = autostartCommand();
  if (process.platform !== 'win32') {
    return { enabled: false, command: null, expected, supported: false, method: null };
  }

  const result = await runReg(['query', RUN_KEY, '/v', VALUE_NAME]);
  const viaFolder = shortcutExists();

  if (result.ok) {
    return { enabled: true, command: expected, expected, supported: true, method: 'registry', stale: false };
  }
  if (viaFolder) {
    return {
      enabled: true,
      command: startupEntryPath(),
      expected,
      supported: true,
      method: 'startup-folder',
      stale: false,
    };
  }
  return {
    enabled: false,
    command: null,
    expected,
    supported: true,
    method: null,
    stale: false,
    // Non-zero simply means "not registered"; only surface it as an error when
    // the registry also cannot be read at all.
    error: undefined,
  };
}

export async function enableAutostart() {
  if (process.platform !== 'win32') {
    return { ok: false, error: 'auto-start is only supported on Windows' };
  }
  const expected = autostartCommand();
  const result = await runReg(['add', RUN_KEY, '/v', VALUE_NAME, '/t', 'REG_SZ', '/d', expected, '/f']);
  if (result.ok) {
    // Keep the two mechanisms from both firing.
    disableViaStartupFolder();
    return { ok: true, enabled: true, command: expected, expected, supported: true, method: 'registry' };
  }

  // The registry is not writable (locked-down or policy-managed machine).
  // Fall back to a Startup-folder shortcut so the feature still works.
  const fallback = enableViaStartupFolder();
  if (fallback.ok) {
    return { ok: true, enabled: true, command: fallback.path, expected, supported: true, method: 'startup-folder' };
  }

  return {
    ok: false,
    error: `could not register auto-start. Registry: ${result.error ?? 'denied'}. Startup folder: ${fallback.error}`,
  };
}

export async function disableAutostart() {
  if (process.platform !== 'win32') {
    return { ok: false, error: 'auto-start is only supported on Windows' };
  }
  const removedFromFolder = disableViaStartupFolder();
  const result = await runReg(['delete', RUN_KEY, '/v', VALUE_NAME, '/f']);

  const status = await getAutostartStatus();
  if (!status.enabled) {
    return { ok: true, enabled: false, expected: autostartCommand(), supported: true, method: null };
  }
  // Still registered somewhere: report why rather than pretending it worked.
  if (!result.ok && !removedFromFolder.ok) {
    return { ok: false, error: result.error ?? removedFromFolder.error ?? 'could not remove the registration' };
  }
  return { ok: true, enabled: false, expected: autostartCommand(), supported: true, method: null };
}

/**
 * Confirm auto-start can actually be registered, so the control panel can
 * disable the toggle instead of offering a switch that silently fails.
 */
export async function isAutostartWritable() {
  if (process.platform !== 'win32') return false;
  if (shortcutExists()) return true;
  const result = await runReg(['query', RUN_KEY], { timeoutMs: 5000 });
  return result.ok;
}

export { RUN_KEY, VALUE_NAME };
